const STATE_FUNDED = "FUNDED";
const STATE_IN_PROGRESS = "IN_PROGRESS";
const STATE_PENDING_APPROVAL = "PENDING_APPROVAL";
const STATE_COMPLETED = "COMPLETED";
const STATE_CANCELLED = "CANCELLED";

const EVENT_JOB_CREATED = "JOB_CREATED";
const EVENT_JOB_ACCEPTED = "JOB_ACCEPTED";
const EVENT_RELEASE_REQUESTED = "RELEASE_REQUESTED";
const EVENT_FUNDS_RELEASED = "FUNDS_RELEASED";
const EVENT_JOB_CANCELLED = "JOB_CANCELLED";

export {
  STATE_FUNDED,
  STATE_IN_PROGRESS,
  STATE_PENDING_APPROVAL,
  STATE_COMPLETED,
  STATE_CANCELLED,
  EVENT_JOB_CREATED,
  EVENT_JOB_ACCEPTED,
  EVENT_RELEASE_REQUESTED,
  EVENT_FUNDS_RELEASED,
  EVENT_JOB_CANCELLED,
};
